[env:esp32s3_cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Tốc độ Serial Monitor (Trùng với Serial.begin trong code)
monitor_speed = 115200

; =========================================================
; CẤU HÌNH BỘ NHỚ CHO ESP32-S3-N16R8 
; =========================================================
; N16 = 16MB Flash, R8 = 8MB OPI PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi 

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3    ; Bật log debug để dễ dò lỗi Camera/WiFi
    ; Nếu cắm cáp qua cổng USB trực tiếp của chip S3 (không qua chip CH340), bỏ comment 2 dòng dưới:
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; =========================================================
; QUẢN LÝ THƯ VIỆN TỰ ĐỘNG (Dependencies)
; =========================================================
lib_deps =
    ; 1. Thư viện xử lý JSON từ Server trả về
    bblanchon/ArduinoJson @ ^6.21.3
    
    ; 2. Thư viện điều khiển màn hình LCD I2C
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    
    ; 3. Thư viện Servo được tối ưu riêng cho timer của ESP32
    madhephaestus/ESP32Servo @ ^1.1.1